[theme]
base = "dark"

# General color setup
#textColor = "#314158"
#primaryColor = "#615fff"
#backgroundColor = "#1d293d"
#secondaryBackgroundColor = "#0f172b"

# Widgets
showWidgetBorder = true
borderColor = "#314158"

# Base text
font = "'Titillium Web':https://fonts.googleapis.com/css2?family=Titillium+Web:wght@300;400;600;700&display=swap"
baseFontWeight = 400
baseFontSize = 14

# Heading text
headingFont = "Titillium Web"
headingFontWeights = [700, 600, 400, 400, 300, 300]
headingFontSizes = ["2.5rem", "1.5rem", "1rem"]
